apiVersion: v1
kind: Pod
metadata:
  name: mytensorflow-balaji
  namespace: cms-ml
spec:
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: gpu-type
                          operator: In
                          values:
                          - A100
    containers:
      - name: mytensorflow-balaji
        image: tensorflow/tensorflow:latest-gpu-py3
        imagePullPolicy: Always
        command: ["bash", "-c", "sleep infinity"]
        resources:
           limits:
             nvidia.com/gpu: 1

